#define APP_VERSION L" V1.2"
#define APP_TIME L" - 2011.03.31"
#define APP_NAME L"DragonNest MSH Converter"
#define APP_INFO APP_NAME APP_VERSION APP_TIME L"\nConverting models between MSH format and general model format.\nFBX supported by Autodesk FBX SDK.\nAuthor:\tGPBeta\nE-Mail:\tstudiocghibli@gmail.com\nWeb:\twww.gpbeta.com"

#define LANG_ERROR L"Error"
#define LANG_WARN L"Warning"
#define LANG_INFO L"Information"
#define LANG_ABOUT L"About the program"
#define LANG_BROWSE L"Browse"
#define LANG_CONVERT L"Convert"
#define LANG_CHOOSE_MODEL L"<-Please pick up a model / MSH file->"
#define LANG_CHOOSE_ANI L"<-(Opt)Pick up an ANI file for the MSH file->"

#define LANG_READY L"Ready"
#define LANG_WORKING L"Working..."
#define LANG_DONE L"SUCCESS!"
#define LANG_FAIL L"FAILURE!"

#define LANG_MSG_REQUIRE_ANI L"Please pick up an ANI file for the MSH file"
#define LANG_MSG_SUCCESS L"File converted successfully!"
#define LANG_MSG_FAILURE L"Fail to convert specify files!\nPlease choose valid files."
#define LANG_MSG_REQUIRE_FILE L"Please specify files for converting!"
#define LANG_MSG_BONE_NOT_FOUND L"Can not find bone below:\n"
#define LANG_MSG_NOT_TRIANGLE L"Mesh below contain one or more non-triangle face:\n"
#define LANG_MSG_QUESTION L"\nContinue anyway?"
